assets:
  rubygems.yml: "yegor256/home#assets/rubygems.yml"
  s3cfg: "yegor256/home#assets/s3cfg"

install: |
  sudo gem install --no-ri --no-rdoc pdd
  sudo apt-get install -y subversion
  sudo apt-get install -y software-properties-common
  sudo add-apt-repository -y ppa:git-core/ppa
  sudo apt-get update
  sudo apt-get remove -y git
  sudo apt-get install -y git

release:
  script: |
    sudo bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/volatility/version.rb
    git commit -m "${tag}" lib/volatility/version.rb
    gem build volatility.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    pdd --source=$(pwd) --verbose --file=volatility.xml
    s3cmd --no-progress put volatility.xml --config=../s3cfg s3://pdd.teamed.io/volatility.xml
