assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" bin/volatility.rb
    sed -i "s/0\.0\.0/${tag}/g" volatility.gemspec
    git add bin/volatility.rb
    git add volatility.gemspec
    git commit -m "version set to ${tag}"
    gem build volatility.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
    pdd -f /dev/null
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
